Windows fixes
rrahn/seqan pull request #3
Opened 2018-01-12 19:51 UTC by marehr

2018-01-15 20:15 UTC, marehr commented
@rrahn simd is also fixed

2018-01-16 07:46 UTC, rrahn requested changes
Some minor remarks left.

2018-01-16 07:46 UTC, rrahn commented on include/seqan/align_parallel/parallel_align_interface.h
> +        using TPos = int;
I would rather be more accurate and use `std::make_signed_t<>` on the decltype of `length`

2018-01-16 07:46 UTC, rrahn commented on include/seqan/align_parallel/parallel_align_interface.h
> +        using TPos = int;
same here.

2018-01-16 07:46 UTC, rrahn commented on util/cmake/seqan-config.cmake
> +  set (SEQAN_DEFINITIONS ${SEQAN_DEFINITIONS} /EHsc /Oi)
When we add here a required compilation flag we should document this somehow in the manual, for people that build extern with VS, don't we?

2018-01-16 08:19 UTC, rrahn approved these changes

2018-01-16 08:19 UTC, merged